In [29]:
import pandas as pd
import numpy as np

In [30]:
df = pd.read_csv("/Users/leonidsim/Desktop/Metis/MTA01-11-2020.txt")

In [31]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 206073 entries, 0 to 206072
Data columns (total 11 columns):
C/A                                                                     206073 non-null object
UNIT                                                                    206073 non-null object
SCP                                                                     206073 non-null object
STATION                                                                 206073 non-null object
LINENAME                                                                206073 non-null object
DIVISION                                                                206073 non-null object
DATE                                                                    206073 non-null object
TIME                                                                    206073 non-null object
DESC                                                                    206073 non-null object
ENTRIES                                                                 206073 non-null int64
EXITS                                                                   206073 non-null int64
dtypes: int64(2), object(9)
memory usage: 17.3+ MB

In [32]:
df['Datetime'] = pd.to_datetime(df['DATE'].apply(str)+' '+df['TIME'])

In [33]:
df.head(20)

,C/A,UNIT,SCP,STATION,LINENAME,DIVISION,DATE,TIME,DESC,ENTRIES,EXITS,Datetime
0,A002,R051,02-00-00,59 ST,NQR456W,BMT,01/04/2020,03:00:00,REGULAR,7331213,2484849,2020-01-04 03:00:00
1,A002,R051,02-00-00,59 ST,NQR456W,BMT,01/04/2020,07:00:00,REGULAR,7331224,2484861,2020-01-04 07:00:00
2,A002,R051,02-00-00,59 ST,NQR456W,BMT,01/04/2020,11:00:00,REGULAR,7331281,2484936,2020-01-04 11:00:00
3,A002,R051,02-00-00,59 ST,NQR456W,BMT,01/04/2020,15:00:00,REGULAR,7331454,2485014,2020-01-04 15:00:00
4,A002,R051,02-00-00,59 ST,NQR456W,BMT,01/04/2020,19:00:00,REGULAR,7331759,2485106,2020-01-04 19:00:00
5,A002,R051,02-00-00,59 ST,NQR456W,BMT,01/04/2020,23:00:00,REGULAR,7331951,2485166,2020-01-04 23:00:00
6,A002,R051,02-00-00,59 ST,NQR456W,BMT,01/05/2020,03:00:00,REGULAR,7331997,2485182,2020-01-05 03:00:00
7,A002,R051,02-00-00,59 ST,NQR456W,BMT,01/05/2020,07:00:00,REGULAR,7332007,2485190,2020-01-05 07:00:00
8,A002,R051,02-00-00,59 ST,NQR456W,BMT,01/05/2020,11:00:00,REGULAR,7332052,2485249,2020-01-05 11:00:00
9,A002,R051,02-00-00,59 ST,NQR456W,BMT,01/05/2020,15:00:00,REGULAR,7332197,2485308,2020-01-05 15:00:00
10,A002,R051,02-00-00,59 ST,NQR456W,BMT,01/05/2020,19:00:00,REGULAR,7332405,2485369,2020-01-05 19:00:00
11,A002,R051,02-00-00,59 ST,NQR456W,BMT,01/05/2020,23:00:00,REGULAR,7332543,2485396,2020-01-05 23:00:00
12,A002,R051,02-00-00,59 ST,NQR456W,BMT,01/06/2020,03:00:00,REGULAR,7332566,2485402,2020-01-06 03:00:00
13,A002,R051,02-00-00,59 ST,NQR456W,BMT,01/06/2020,07:00:00,REGULAR,7332574,2485431,2020-01-06 07:00:00
14,A002,R051,02-00-00,59 ST,NQR456W,BMT,01/06/2020,11:00:00,REGULAR,7332705,2485725,2020-01-06 11:00:00
15,A002,R051,02-00-00,59 ST,NQR456W,BMT,01/06/2020,15:00:00,REGULAR,7332892,2485801,2020-01-06 15:00:00
16,A002,R051,02-00-00,59 ST,NQR456W,BMT,01/06/2020,19:00:00,REGULAR,7333645,2485891,2020-01-06 19:00:00
17,A002,R051,02-00-00,59 ST,NQR456W,BMT,01/06/2020,23:00:00,REGULAR,7333879,2485925,2020-01-06 23:00:00
18,A002,R051,02-00-00,59 ST,NQR456W,BMT,01/07/2020,03:00:00,REGULAR,7333906,2485935,2020-01-07 03:00:00
19,A002,R051,02-00-00,59 ST,NQR456W,BMT,01/07/2020,07:00:00,REGULAR,7333921,2485986,2020-01-07 07:00:00

In [34]:
df['Turnstile'] = df['C/A'] + df['UNIT'] + df['SCP']

In [35]:
df.head()

,C/A,UNIT,SCP,STATION,LINENAME,DIVISION,DATE,TIME,DESC,ENTRIES,EXITS,Datetime,Turnstile
0,A002,R051,02-00-00,59 ST,NQR456W,BMT,01/04/2020,03:00:00,REGULAR,7331213,2484849,2020-01-04 03:00:00,A002R05102-00-00
1,A002,R051,02-00-00,59 ST,NQR456W,BMT,01/04/2020,07:00:00,REGULAR,7331224,2484861,2020-01-04 07:00:00,A002R05102-00-00
2,A002,R051,02-00-00,59 ST,NQR456W,BMT,01/04/2020,11:00:00,REGULAR,7331281,2484936,2020-01-04 11:00:00,A002R05102-00-00
3,A002,R051,02-00-00,59 ST,NQR456W,BMT,01/04/2020,15:00:00,REGULAR,7331454,2485014,2020-01-04 15:00:00,A002R05102-00-00
4,A002,R051,02-00-00,59 ST,NQR456W,BMT,01/04/2020,19:00:00,REGULAR,7331759,2485106,2020-01-04 19:00:00,A002R05102-00-00

In [40]:
df["Day_Name"] = df["Datetime"].dt.day_name()

In [42]:
df.head(50)

,C/A,UNIT,SCP,STATION,LINENAME,DIVISION,DATE,TIME,DESC,ENTRIES,EXITS,Datetime,Turnstile,Day_Name
0,A002,R051,02-00-00,59 ST,NQR456W,BMT,01/04/2020,03:00:00,REGULAR,7331213,2484849,2020-01-04 03:00:00,A002R05102-00-00,Saturday
1,A002,R051,02-00-00,59 ST,NQR456W,BMT,01/04/2020,07:00:00,REGULAR,7331224,2484861,2020-01-04 07:00:00,A002R05102-00-00,Saturday
2,A002,R051,02-00-00,59 ST,NQR456W,BMT,01/04/2020,11:00:00,REGULAR,7331281,2484936,2020-01-04 11:00:00,A002R05102-00-00,Saturday
3,A002,R051,02-00-00,59 ST,NQR456W,BMT,01/04/2020,15:00:00,REGULAR,7331454,2485014,2020-01-04 15:00:00,A002R05102-00-00,Saturday
4,A002,R051,02-00-00,59 ST,NQR456W,BMT,01/04/2020,19:00:00,REGULAR,7331759,2485106,2020-01-04 19:00:00,A002R05102-00-00,Saturday
5,A002,R051,02-00-00,59 ST,NQR456W,BMT,01/04/2020,23:00:00,REGULAR,7331951,2485166,2020-01-04 23:00:00,A002R05102-00-00,Saturday
6,A002,R051,02-00-00,59 ST,NQR456W,BMT,01/05/2020,03:00:00,REGULAR,7331997,2485182,2020-01-05 03:00:00,A002R05102-00-00,Sunday
7,A002,R051,02-00-00,59 ST,NQR456W,BMT,01/05/2020,07:00:00,REGULAR,7332007,2485190,2020-01-05 07:00:00,A002R05102-00-00,Sunday
8,A002,R051,02-00-00,59 ST,NQR456W,BMT,01/05/2020,11:00:00,REGULAR,7332052,2485249,2020-01-05 11:00:00,A002R05102-00-00,Sunday
9,A002,R051,02-00-00,59 ST,NQR456W,BMT,01/05/2020,15:00:00,REGULAR,7332197,2485308,2020-01-05 15:00:00,A002R05102-00-00,Sunday
10,A002,R051,02-00-00,59 ST,NQR456W,BMT,01/05/2020,19:00:00,REGULAR,7332405,2485369,2020-01-05 19:00:00,A002R05102-00-00,Sunday
11,A002,R051,02-00-00,59 ST,NQR456W,BMT,01/05/2020,23:00:00,REGULAR,7332543,2485396,2020-01-05 23:00:00,A002R05102-00-00,Sunday
12,A002,R051,02-00-00,59 ST,NQR456W,BMT,01/06/2020,03:00:00,REGULAR,7332566,2485402,2020-01-06 03:00:00,A002R05102-00-00,Monday
13,A002,R051,02-00-00,59 ST,NQR456W,BMT,01/06/2020,07:00:00,REGULAR,7332574,2485431,2020-01-06 07:00:00,A002R05102-00-00,Monday
14,A002,R051,02-00-00,59 ST,NQR456W,BMT,01/06/2020,11:00:00,REGULAR,7332705,2485725,2020-01-06 11:00:00,A002R05102-00-00,Monday
15,A002,R051,02-00-00,59 ST,NQR456W,BMT,01/06/2020,15:00:00,REGULAR,7332892,2485801,2020-01-06 15:00:00,A002R05102-00-00,Monday
16,A002,R051,02-00-00,59 ST,NQR456W,BMT,01/06/2020,19:00:00,REGULAR,7333645,2485891,2020-01-06 19:00:00,A002R05102-00-00,Monday
17,A002,R051,02-00-00,59 ST,NQR456W,BMT,01/06/2020,23:00:00,REGULAR,7333879,2485925,2020-01-06 23:00:00,A002R05102-00-00,Monday
18,A002,R051,02-00-00,59 ST,NQR456W,BMT,01/07/2020,03:00:00,REGULAR,7333906,2485935,2020-01-07 03:00:00,A002R05102-00-00,Tuesday
19,A002,R051,02-00-00,59 ST,NQR456W,BMT,01/07/2020,07:00:00,REGULAR,7333921,2485986,2020-01-07 07:00:00,A002R05102-00-00,Tuesday
20,A002,R051,02-00-00,59 ST,NQR456W,BMT,01/07/2020,11:00:00,REGULAR,7334052,2486261,2020-01-07 11:00:00,A002R05102-00-00,Tuesday
21,A002,R051,02-00-00,59 ST,NQR456W,BMT,01/07/2020,15:00:00,REGULAR,7334252,2486319,2020-01-07 15:00:00,A002R05102-00-00,Tuesday
22,A002,R051,02-00-00,59 ST,NQR456W,BMT,01/07/2020,19:00:00,REGULAR,7335008,2486391,2020-01-07 19:00:00,A002R05102-00-00,Tuesday
23,A002,R051,02-00-00,59 ST,NQR456W,BMT,01/07/2020,23:00:00,REGULAR,7335258,2486432,2020-01-07 23:00:00,A002R05102-00-00,Tuesday
24,A002,R051,02-00-00,59 ST,NQR456W,BMT,01/08/2020,03:00:00,REGULAR,7335289,2486442,2020-01-08 03:00:00,A002R05102-00-00,Wednesday
25,A002,R051,02-00-00,59 ST,NQR456W,BMT,01/08/2020,07:00:00,REGULAR,7335300,2486484,2020-01-08 07:00:00,A002R05102-00-00,Wednesday
26,A002,R051,02-00-00,59 ST,NQR456W,BMT,01/08/2020,11:00:00,REGULAR,7335421,2486784,2020-01-08 11:00:00,A002R05102-00-00,Wednesday
27,A002,R051,02-00-00,59 ST,NQR456W,BMT,01/08/2020,15:00:00,REGULAR,7335598,2486878,2020-01-08 15:00:00,A002R05102-00-00,Wednesday
28,A002,R051,02-00-00,59 ST,NQR456W,BMT,01/08/2020,19:00:00,REGULAR,7336416,2486951,2020-01-08 19:00:00,A002R05102-00-00,Wednesday
29,A002,R051,02-00-00,59 ST,NQR456W,BMT,01/08/2020,23:00:00,REGULAR,7336688,2486986,2020-01-08 23:00:00,A002R05102-00-00,Wednesday
30,A002,R051,02-00-00,59 ST,NQR456W,BMT,01/09/2020,03:00:00,REGULAR,7336735,2486993,2020-01-09 03:00:00,A002R05102-00-00,Thursday
31,A002,R051,02-00-00,59 ST,NQR456W,BMT,01/09/2020,07:00:00,REGULAR,7336751,2487029,2020-01-09 07:00:00,A002R05102-00-00,Thursday
32,A002,R051,02-00-00,59 ST,NQR456W,BMT,01/09/2020,11:00:00,REGULAR,7336881,2487190,2020-01-09 11:00:00,A002R05102-00-00,Thursday
33,A002,R051,02-00-00,59 ST,NQR456W,BMT,01/09/2020,15:00:00,REGULAR,7337095,2487247,2020-01-09 15:00:00,A002R05102-00-00,Thursday
34,A002,R051,02-00-00,59 ST,NQR456W,BMT,01/09/2020,19:00:00,REGULAR,7337862,2487331,2020-01-09 19:00:00,A002R05102-00-00,Thursday
35,A002,R051,02-00-00,59 ST,NQR456W,BMT,01/09/2020,23:00:00,REGULAR,7338122,2487370,2020-01-09 23:00:00,A002R05102-00-00,Thursday
36,A002,R051,02-00-00,59 ST,NQR456W,BMT,01/10/2020,03:00:00,REGULAR,7338161,2487377,2020-01-10 03:00:00,A002R05102-00-00,Friday
37,A002,R051,02-00-00,59 ST,NQR456W,BMT,01/10/2020,07:00:00,REGULAR,7338175,2487416,2020-01-10 07:00:00,A002R05102-00-00,Friday
38,A002,R051,02-00-00,59 ST,NQR456W,BMT,01/10/2020,11:00:00,REGULAR,7338300,2487692,2020-01-10 11:00:00,A002R05102-00-00,Friday
39,A002,R051,02-00-00,59 ST,NQR456W,BMT,01/10/2020,15:00:00,REGULAR,7338545,2487754,2020-01-10 15:00:00,A002R05102-00-00,Friday
40,A002,R051,02-00-00,59 ST,NQR456W,BMT,01/10/2020,19:00:00,REGULAR,7339294,2487838,2020-01-10 19:00:00,A002R05102-00-00,Friday
41,A002,R051,02-00-00,59 ST,NQR456W,BMT,01/10/2020,23:00:00,REGULAR,7339564,2487872,2020-01-10 23:00:00,A002R05102-00-00,Friday
42,A002,R051,02-00-01,59 ST,NQR456W,BMT,01/04/2020,03:00:00,REGULAR,6514611,1464118,2020-01-04 03:00:00,A002R05102-00-01,Saturday
43,A002,R051,02-00-01,59 ST,NQR456W,BMT,01/04/2020,07:00:00,REGULAR,6514617,1464127,2020-01-04 07:00:00,A002R05102-00-01,Saturday
44,A002,R051,02-00-01,59 ST,NQR456W,BMT,01/04/2020,11:00:00,REGULAR,6514670,1464184,2020-01-04 11:00:00,A002R05102-00-01,Saturday
45,A002,R051,02-00-01,59 ST,NQR456W,BMT,01/04/2020,15:00:00,REGULAR,6514886,1464234,2020-01-04 15:00:00,A002R05102-00-01,Saturday
46,A002,R051,02-00-01,59 ST,NQR456W,BMT,01/04/2020,19:00:00,REGULAR,6515161,1464292,2020-01-04 19:00:00,A002R05102-00-01,Saturday
47,A002,R051,02-00-01,59 ST,NQR456W,BMT,01/04/2020,23:00:00,REGULAR,6515347,1464321,2020-01-04 23:00:00,A002R05102-00-01,Saturday
48,A002,R051,02-00-01,59 ST,NQR456W,BMT,01/05/2020,03:00:00,REGULAR,6515399,1464333,2020-01-05 03:00:00,A002R05102-00-01,Sunday
49,A002,R051,02-00-01,59 ST,NQR456W,BMT,01/05/2020,07:00:00,REGULAR,6515405,1464340,2020-01-05 07:00:00,A002R05102-00-01,Sunday

In [93]:
mask = df['Day_Name'] != 'Saturday'

In [94]:
df_weekdays = df[(df["Day_Name"] != "Saturday") & (df["Day_Name"] != "Sunday")]

In [95]:
df_final = df_weekdays[(df_weekdays["TIME"] >= "07:00:00") & (df_weekdays["TIME"] <= "11:00:00")]

In [96]:
df_final_2 = df_final.groupby(['Turnstile','DATE'])

df_final.groupby(['Turnstile','DATE']).transform(lambda g: g.shift(-1) - g)

,C/A,UNIT,SCP,STATION,LINENAME,DIVISION,DATE,TIME,DESC,ENTRIES,EXITS,Datetime,Turnstile,Day_Name
13,A002,R051,02-00-00,59 ST,NQR456W,BMT,01/06/2020,07:00:00,REGULAR,7332574,2485431,2020-01-06 07:00:00,A002R05102-00-00,Monday
14,A002,R051,02-00-00,59 ST,NQR456W,BMT,01/06/2020,11:00:00,REGULAR,7332705,2485725,2020-01-06 11:00:00,A002R05102-00-00,Monday
19,A002,R051,02-00-00,59 ST,NQR456W,BMT,01/07/2020,07:00:00,REGULAR,7333921,2485986,2020-01-07 07:00:00,A002R05102-00-00,Tuesday
20,A002,R051,02-00-00,59 ST,NQR456W,BMT,01/07/2020,11:00:00,REGULAR,7334052,2486261,2020-01-07 11:00:00,A002R05102-00-00,Tuesday
25,A002,R051,02-00-00,59 ST,NQR456W,BMT,01/08/2020,07:00:00,REGULAR,7335300,2486484,2020-01-08 07:00:00,A002R05102-00-00,Wednesday
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
206045,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,01/06/2020,08:00:00,REGULAR,5554,420,2020-01-06 08:00:00,TRAM2R46900-05-01,Monday
206051,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,01/07/2020,08:00:00,REGULAR,5554,420,2020-01-07 08:00:00,TRAM2R46900-05-01,Tuesday
206057,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,01/08/2020,08:00:00,REGULAR,5554,420,2020-01-08 08:00:00,TRAM2R46900-05-01,Wednesday
206063,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,01/09/2020,08:00:00,REGULAR,5554,420,2020-01-09 08:00:00,TRAM2R46900-05-01,Thursday
206069,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,01/10/2020,08:00:00,REGULAR,5554,420,2020-01-10 08:00:00,TRAM2R46900-05-01,Friday

In [97]:
df_final_2['Daily'] = df_final
daily_max = df_final.groupby(['Turnstile','DATE']).agg({'ENTRIES': 'max'}).reset_index()
daily.head(100)

7332574 - 7332705
#A002R05102-00-00

-131

In [79]:
#daily_max = df_full.groupby(['Turnstile',‘DATE’]).agg({'Entiries':‘max’}).reset_index()

df_final[df_final['Turnstile']== 'A002R05102-00-00']

,C/A,UNIT,SCP,STATION,LINENAME,DIVISION,DATE,TIME,DESC,ENTRIES,EXITS,Datetime,Turnstile,Day_Name
13,A002,R051,02-00-00,59 ST,NQR456W,BMT,01/06/2020,07:00:00,REGULAR,7332574,2485431,2020-01-06 07:00:00,A002R05102-00-00,Monday
14,A002,R051,02-00-00,59 ST,NQR456W,BMT,01/06/2020,11:00:00,REGULAR,7332705,2485725,2020-01-06 11:00:00,A002R05102-00-00,Monday
19,A002,R051,02-00-00,59 ST,NQR456W,BMT,01/07/2020,07:00:00,REGULAR,7333921,2485986,2020-01-07 07:00:00,A002R05102-00-00,Tuesday
20,A002,R051,02-00-00,59 ST,NQR456W,BMT,01/07/2020,11:00:00,REGULAR,7334052,2486261,2020-01-07 11:00:00,A002R05102-00-00,Tuesday
25,A002,R051,02-00-00,59 ST,NQR456W,BMT,01/08/2020,07:00:00,REGULAR,7335300,2486484,2020-01-08 07:00:00,A002R05102-00-00,Wednesday
26,A002,R051,02-00-00,59 ST,NQR456W,BMT,01/08/2020,11:00:00,REGULAR,7335421,2486784,2020-01-08 11:00:00,A002R05102-00-00,Wednesday
31,A002,R051,02-00-00,59 ST,NQR456W,BMT,01/09/2020,07:00:00,REGULAR,7336751,2487029,2020-01-09 07:00:00,A002R05102-00-00,Thursday
32,A002,R051,02-00-00,59 ST,NQR456W,BMT,01/09/2020,11:00:00,REGULAR,7336881,2487190,2020-01-09 11:00:00,A002R05102-00-00,Thursday
37,A002,R051,02-00-00,59 ST,NQR456W,BMT,01/10/2020,07:00:00,REGULAR,7338175,2487416,2020-01-10 07:00:00,A002R05102-00-00,Friday
38,A002,R051,02-00-00,59 ST,NQR456W,BMT,01/10/2020,11:00:00,REGULAR,7338300,2487692,2020-01-10 11:00:00,A002R05102-00-00,Friday

In [80]:
#Take the max entries for a turnstile - min entries for turnstile = For each turnstile, delta 

monthly_max = 

daily_min = df_final.groupby(['Turnstile','DATE']).agg({'ENTRIES': 'min'}).reset_index()
daily_min.head(100)

           Turnstile        DATE  ENTRIES
0   A002R05102-00-00  01/06/2020  7332574
1   A002R05102-00-00  01/07/2020  7333921
2   A002R05102-00-00  01/08/2020  7335300
3   A002R05102-00-00  01/09/2020  7336751
4   A002R05102-00-00  01/10/2020  7338175
..               ...         ...      ...
95  A006R07900-03-02  01/06/2020   843231
96  A006R07900-03-02  01/07/2020   845295
97  A006R07900-03-02  01/08/2020   847458
98  A006R07900-03-02  01/09/2020   849662
99  A006R07900-03-02  01/10/2020   851894

[100 rows x 3 columns]

In [82]:
df_final['Delta'] = daily_max['ENTRIES'] - daily_min['ENTRIES']

/Users/leonidsim/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

In [83]:
df_final.head(100)

,C/A,UNIT,SCP,STATION,LINENAME,DIVISION,DATE,TIME,DESC,ENTRIES,EXITS,Datetime,Turnstile,Day_Name,Delta
13,A002,R051,02-00-00,59 ST,NQR456W,BMT,01/06/2020,07:00:00,REGULAR,7332574,2485431,2020-01-06 07:00:00,A002R05102-00-00,Monday,67.0
14,A002,R051,02-00-00,59 ST,NQR456W,BMT,01/06/2020,11:00:00,REGULAR,7332705,2485725,2020-01-06 11:00:00,A002R05102-00-00,Monday,53.0
19,A002,R051,02-00-00,59 ST,NQR456W,BMT,01/07/2020,07:00:00,REGULAR,7333921,2485986,2020-01-07 07:00:00,A002R05102-00-00,Tuesday,126.0
20,A002,R051,02-00-00,59 ST,NQR456W,BMT,01/07/2020,11:00:00,REGULAR,7334052,2486261,2020-01-07 11:00:00,A002R05102-00-00,Tuesday,161.0
25,A002,R051,02-00-00,59 ST,NQR456W,BMT,01/08/2020,07:00:00,REGULAR,7335300,2486484,2020-01-08 07:00:00,A002R05102-00-00,Wednesday,169.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
404,A002,R051,02-05-00,59 ST,NQR456W,BMT,01/08/2020,11:00:00,REGULAR,57,0,2020-01-08 11:00:00,A002R05102-05-00,Wednesday,953.0
409,A002,R051,02-05-00,59 ST,NQR456W,BMT,01/09/2020,07:00:00,REGULAR,57,0,2020-01-09 07:00:00,A002R05102-05-00,Thursday,911.0
410,A002,R051,02-05-00,59 ST,NQR456W,BMT,01/09/2020,11:00:00,REGULAR,57,0,2020-01-09 11:00:00,A002R05102-05-00,Thursday,929.0
415,A002,R051,02-05-00,59 ST,NQR456W,BMT,01/10/2020,07:00:00,REGULAR,57,0,2020-01-10 07:00:00,A002R05102-05-00,Friday,796.0
416,A002,R051,02-05-00,59 ST,NQR456W,BMT,01/10/2020,11:00:00,REGULAR,58,0,2020-01-10 11:00:00,A002R05102-05-00,Friday,795.0

In [85]:
df_final[df_final['Turnstile']== 'A002R05102-00-00']

,C/A,UNIT,SCP,STATION,LINENAME,DIVISION,DATE,TIME,DESC,ENTRIES,EXITS,Datetime,Turnstile,Day_Name,Delta
13,A002,R051,02-00-00,59 ST,NQR456W,BMT,01/06/2020,07:00:00,REGULAR,7332574,2485431,2020-01-06 07:00:00,A002R05102-00-00,Monday,67.0
14,A002,R051,02-00-00,59 ST,NQR456W,BMT,01/06/2020,11:00:00,REGULAR,7332705,2485725,2020-01-06 11:00:00,A002R05102-00-00,Monday,53.0
19,A002,R051,02-00-00,59 ST,NQR456W,BMT,01/07/2020,07:00:00,REGULAR,7333921,2485986,2020-01-07 07:00:00,A002R05102-00-00,Tuesday,126.0
20,A002,R051,02-00-00,59 ST,NQR456W,BMT,01/07/2020,11:00:00,REGULAR,7334052,2486261,2020-01-07 11:00:00,A002R05102-00-00,Tuesday,161.0
25,A002,R051,02-00-00,59 ST,NQR456W,BMT,01/08/2020,07:00:00,REGULAR,7335300,2486484,2020-01-08 07:00:00,A002R05102-00-00,Wednesday,169.0
26,A002,R051,02-00-00,59 ST,NQR456W,BMT,01/08/2020,11:00:00,REGULAR,7335421,2486784,2020-01-08 11:00:00,A002R05102-00-00,Wednesday,168.0
31,A002,R051,02-00-00,59 ST,NQR456W,BMT,01/09/2020,07:00:00,REGULAR,7336751,2487029,2020-01-09 07:00:00,A002R05102-00-00,Thursday,208.0
32,A002,R051,02-00-00,59 ST,NQR456W,BMT,01/09/2020,11:00:00,REGULAR,7336881,2487190,2020-01-09 11:00:00,A002R05102-00-00,Thursday,209.0
37,A002,R051,02-00-00,59 ST,NQR456W,BMT,01/10/2020,07:00:00,REGULAR,7338175,2487416,2020-01-10 07:00:00,A002R05102-00-00,Friday,383.0
38,A002,R051,02-00-00,59 ST,NQR456W,BMT,01/10/2020,11:00:00,REGULAR,7338300,2487692,2020-01-10 11:00:00,A002R05102-00-00,Friday,364.0

In [90]:
7335300 - 7335421

-121

In [87]:
67 + 53

120

In [98]:
!pwd

/Users/leonidsim/Desktop/Metis/nyc20_ds23/curriculum/project-01/matplotlib